### ISSUE TITLE
Mini-crud create new records when you are trying to delete others

### ISSUE THREAD

**Issue by jnegreira** [anavel/crud#23]
Case:
1. Minicrud, with a field selectable from a list (select component, created by "defaults" option)
2. Minicrud tab shows some stored records, and at the bottom, the form to add a new record. In this form, the select component has the first element selected
3. Try to delete the first record, checking the "delete check", and clicking "save"
4. Controller receive the delete action, and the form for new record filled with the "select field", so, it creates a new record, too.

**Comment by cmoralesweb** [comment]
Just add an empty value in the defaults array:

```
 'defaults'   => [
                            'type' => [
                                '' => '',
                                'one' => 'One value',
                                'two        => 'Another Value'
                            ]
                        ]
```
