### ISSUE TITLE
How to access Admin Panel

### ISSUE THREAD

**Issue by richardkeep** [anavel/crud#35]
How does one access the admin panel after editing the config file?

**Comment by ablunier** [comment]
Hi @richardkeep !

Anavel is a modular CMS, so accessing the admin panel is not crud module's responsibility. The [anavel/foundation](https://github.com/anavel/foundation) package is responsible for this. Within it we are planning to implement various authentication drivers, but by now works only with the built in by laravel. So, you must implement the [Anavel Authenticatable interface](https://github.com/anavel/foundation/blob/master/src/Contracts/Authenticatable.php) with your User model and create a user (with a seeder for example). After this, you will be able to access the admin panel.

By the way, Anavel is in an alpha version and we are currently working on a more stable version, so sorry for the lack of documentation. We are also currently working on the documentation and will be released soon. You can check it at http://anavel.anavallasuiza.com

**Comment by richardkeep** [comment]
Thanks for the explanation. I was just appalled by how scanty the documentation is.
